# Generated by Django 6.0.6 on 2026-06-28 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('max_users', models.PositiveIntegerField(default=10)),
                ('max_rooms', models.PositiveIntegerField(default=50)),
                ('restaurant_support', models.BooleanField(default=True)),
                ('reports_support', models.BooleanField(default=True)),
                ('trial_support', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'فعالة'), ('suspended', 'موقوفة'), ('archived', 'مؤرشفة')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='is_active',
        ),
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='hotel',
            name='floors_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hotel',
            name='manager_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='hotel',
            name='manager_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='hotel',
            name='manager_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_hotel', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='hotel',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('suspended', 'موقوف'), ('archived', 'مؤرشف')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('receptionist', 'موظف استقبال'), ('cashier', 'كاشير'), ('housekeeping', 'تنظيف'), ('maintenance', 'صيانة'), ('restaurant', 'مطعم'), ('room_service', 'خدمة غرف'), ('supervisor', 'مشرف')], max_length=30)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('shift', models.CharField(choices=[('morning', 'صباحية'), ('evening', 'مسائية'), ('night', 'ليلية'), ('flexible', 'حسب الحاجة')], default='morning', max_length=20)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('suspended', 'موقوف'), ('archived', 'مؤرشف')], default='active', max_length=20)),
                ('permissions', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='api.hotel')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'تجريبي'), ('active', 'فعال'), ('expired', 'منتهي'), ('suspended', 'موقوف'), ('not_set', 'غير مضبوط')], default='trial', max_length=20)),
                ('payment_status', models.CharField(choices=[('paid', 'مدفوع'), ('unpaid', 'غير مدفوع'), ('partial', 'جزئي')], default='unpaid', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('monthly_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='api.hotel')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.package')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق'), ('rejected', 'مرفوض')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_requests', to='api.hotel')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.package')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('floor', models.PositiveIntegerField(default=1)),
                ('type', models.CharField(choices=[('single', 'مفردة'), ('double', 'مزدوجة'), ('triple', 'ثلاثية'), ('suite', 'سويت'), ('family', 'عائلية'), ('deluxe', 'مميزة')], default='single', max_length=30)),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('status', models.CharField(choices=[('available', 'متاحة'), ('occupied', 'مشغولة'), ('cleaning', 'تنظيف'), ('maintenance', 'صيانة'), ('out_of_service', 'خارج الخدمة'), ('archived', 'مؤرشفة')], default='available', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.hotel')),
            ],
            options={
                'ordering': ['floor', 'number'],
                'unique_together': {('hotel', 'number')},
            },
        ),
    ]
