# Generated by Django 5.1.4 on 2026-06-28 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_package_alter_hotel_options_remove_hotel_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(blank=True, max_length=30)),
                ('guest_id_number', models.CharField(blank=True, max_length=50)),
                ('guest_first_name', models.CharField(blank=True, max_length=100)),
                ('guest_last_name', models.CharField(blank=True, max_length=100)),
                ('guest_father_name', models.CharField(blank=True, max_length=100)),
                ('guest_mother_name', models.CharField(blank=True, max_length=100)),
                ('guest_dob', models.DateField(blank=True, null=True)),
                ('guest_phone', models.CharField(blank=True, max_length=50)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('has_companions', models.BooleanField(default=False)),
                ('companion_type', models.CharField(blank=True, max_length=20)),
                ('companion_adults_count', models.PositiveIntegerField(default=0)),
                ('companion_children_count', models.PositiveIntegerField(default=0)),
                ('companion_children_relation', models.CharField(blank=True, max_length=50)),
                ('companions', models.JSONField(default=list)),
                ('guest_doc_type', models.CharField(blank=True, max_length=50)),
                ('guest_doc_image', models.TextField(blank=True)),
                ('family_doc_type', models.CharField(blank=True, max_length=50)),
                ('family_doc_image', models.TextField(blank=True)),
                ('companion_docs', models.JSONField(default=list)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('nights_count', models.PositiveIntegerField(default=1)),
                ('persons_count', models.PositiveIntegerField(default=1)),
                ('room_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('checked_in', 'تم تسجيل الدخول'), ('checked_out', 'تم تسجيل الخروج'), ('cancelled', 'ملغي'), ('no_show', 'لم يحضر')], default='pending', max_length=20)),
                ('source', models.CharField(choices=[('direct', 'مباشر'), ('phone', 'هاتف'), ('website', 'موقع إلكتروني'), ('ota', 'منصة حجز')], default='direct', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='api.hotel')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='api.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
