# Generated by Django 5.1.4 on 2026-06-28 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(blank=True, max_length=20)),
                ('issue_type', models.CharField(choices=[('electric', 'كهرباء'), ('plumbing', 'سباكة'), ('ac', 'تكييف'), ('internet', 'إنترنت'), ('furniture', 'أثاث'), ('appliance', 'جهاز/معدات'), ('door', 'أبواب وأقفال'), ('cleaning_damage', 'ملاحظة تنظيف/تلف'), ('other', 'أخرى')], default='other', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'مرتفعة'), ('urgent', 'عاجلة')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('in_progress', 'قيد المعالجة'), ('waiting_parts', 'بانتظار قطع'), ('resolved', 'تم الإنجاز'), ('cancelled', 'ملغي')], default='open', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'يدوي'), ('housekeeping', 'من التنظيف'), ('room_status', 'من حالة الغرفة')], default='manual', max_length=30)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance', to='api.staff')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tickets', to='api.hotel')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tickets', to='api.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
