# Generated by Django 5.1.4 on 2026-06-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='package',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='package',
            name='price',
        ),
        migrations.RemoveField(
            model_name='package',
            name='reports_support',
        ),
        migrations.RemoveField(
            model_name='package',
            name='restaurant_support',
        ),
        migrations.RemoveField(
            model_name='package',
            name='trial_support',
        ),
        migrations.AddField(
            model_name='package',
            name='features',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='max_staff',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='package',
            name='price_monthly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='price_yearly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
