# Generated by Django 5.1.4 on 2026-06-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_subscriptionrequest_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='hotel',
            name='cancellation_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_in_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_out_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='cover_image',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='hotel',
            name='gallery_images',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='hotel',
            name='governorate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_type',
            field=models.CharField(blank=True, choices=[('hotel', 'فندق'), ('apart_hotel', 'شقق فندقية'), ('resort', 'منتجع'), ('guesthouse', 'نزل'), ('motel', 'موتيل')], max_length=30),
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='map_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='hotel',
            name='payment_policy',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='public_booking_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='public_description_full',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='public_description_short',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='public_listing_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='show_contact_info',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='stars',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='allow_featured_placement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='allow_public_booking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='package',
            name='allow_public_listing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='arrival_status',
            field=models.CharField(blank=True, choices=[('awaiting_arrival', 'بانتظار الوصول'), ('arrived', 'وصل إلى الفندق'), ('checked_in_w', 'تم تسجيل الدخول'), ('completed_w', 'مكتمل'), ('cancelled_by_guest', 'ملغى من الزبون'), ('cancelled_by_hotel', 'ملغى من الفندق'), ('no_show_w', 'لم يحضر')], default='awaiting_arrival', max_length=30),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancel_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancelled_by_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='documents_status',
            field=models.CharField(blank=True, default='pending_on_arrival', max_length=30),
        ),
        migrations.AddField(
            model_name='reservation',
            name='no_show_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(blank=True, default='direct', max_length=30),
        ),
        migrations.AddField(
            model_name='reservation',
            name='platform_commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='platform_commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='reservation',
            name='public_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='public_booking_no',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room_type_label',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='public_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='room',
            name='show_in_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='source',
            field=models.CharField(choices=[('direct', 'مباشر'), ('phone', 'هاتف'), ('website', 'موقع إلكتروني'), ('ota', 'منصة حجز'), ('public_website', 'الموقع العام')], default='direct', max_length=20),
        ),
    ]
