# Generated by Django 5.1.4 on 2026-06-30 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_public_website_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRevenueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_booking_commission', models.BooleanField(default=True)),
                ('default_commission_type', models.CharField(choices=[('percentage', 'نسبة مئوية'), ('fixed_per_booking', 'مبلغ مقطوع لكل حجز'), ('fixed_per_guest', 'مبلغ مقطوع لكل زبون')], default='percentage', max_length=30)),
                ('default_commission_value', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('default_commission_currency', models.CharField(default='USD', max_length=10)),
                ('calculate_commission_on_status', models.CharField(choices=[('on_booking_created', 'عند إنشاء الحجز'), ('on_guest_arrived', 'عند وصول الزبون'), ('on_check_in', 'عند تسجيل الدخول'), ('on_completed', 'عند اكتمال الحجز')], default='on_check_in', max_length=30)),
                ('allow_hotel_override', models.BooleanField(default=True)),
                ('no_show_policy', models.CharField(choices=[('waive', 'إعفاء العمولة'), ('keep', 'إبقاؤها مستحقة')], default='waive', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات أرباح المنصة',
            },
        ),
        migrations.CreateModel(
            name='BookingCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_booking_no', models.CharField(blank=True, max_length=30)),
                ('commission_type_at_booking', models.CharField(blank=True, max_length=30)),
                ('commission_value_at_booking', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_currency_at_booking', models.CharField(default='USD', max_length=10)),
                ('calculated_amount_at_booking', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('calculation_base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('calculation_base_currency', models.CharField(default='USD', max_length=10)),
                ('commission_type', models.CharField(blank=True, max_length=30)),
                ('commission_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_currency', models.CharField(default='USD', max_length=10)),
                ('commission_status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('due', 'مستحقة'), ('paid', 'مدفوعة'), ('partial', 'مدفوعة جزئيًا'), ('waived', 'معفاة'), ('cancelled', 'ملغاة')], default='pending', max_length=20)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_commissions', to='api.hotel')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='api.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HotelCommissionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_enabled', models.BooleanField(default=True)),
                ('commission_type', models.CharField(choices=[('percentage', 'نسبة مئوية'), ('fixed_per_booking', 'مبلغ مقطوع لكل حجز'), ('fixed_per_guest', 'مبلغ مقطوع لكل زبون')], default='percentage', max_length=30)),
                ('commission_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('commission_currency', models.CharField(default='USD', max_length=10)),
                ('commission_notes', models.TextField(blank=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_setting', to='api.hotel')),
            ],
        ),
    ]
