# Generated by Django 5.1.4 on 2026-07-01 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_hotelrating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['hotel', 'status'], name='api_reserva_hotel_i_c48438_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['hotel', 'check_in_date', 'check_out_date'], name='api_reserva_hotel_i_136563_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['public_booking'], name='api_reserva_public__0c03fd_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['hotel', 'status'], name='api_room_hotel_i_eec441_idx'),
        ),
    ]
