# Generated by Django 5.1.4 on 2026-07-01 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_reservation_api_reserva_hotel_i_c48438_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=80)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('spent_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='api.hotel')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hotel', 'spent_on'], name='api_expense_hotel_i_a4af91_idx')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('method', models.CharField(choices=[('cash', 'نقدًا'), ('card', 'بطاقة'), ('transfer', 'تحويل'), ('other', 'أخرى')], default='cash', max_length=20)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('receipt_no', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.hotel')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='api.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hotel', 'created_at'], name='api_payment_hotel_i_edb58e_idx'), models.Index(fields=['reservation'], name='api_payment_reserva_5c0098_idx')],
            },
        ),
    ]
