# Generated by Django 5.1.4 on 2026-07-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_expense_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_to',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
