# Generated by Django 5.1.4 on 2026-07-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_expense_notes_expense_paid_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='funduqii', max_length=120)),
                ('subtitle', models.CharField(blank=True, default='نظام إدارة الفنادق', max_length=200)),
                ('logo_url', models.URLField(blank=True, max_length=1000)),
                ('favicon_url', models.URLField(blank=True, max_length=1000)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('default_country', models.CharField(blank=True, default='سوريا', max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات المنصّة',
            },
        ),
    ]
