# Generated by Django 5.1.4 on 2026-07-01 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_platformsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostFoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=40)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('found', 'موجود'), ('returned', 'أُعيد'), ('unclaimed', 'غير مُطالَب')], default='found', max_length=20)),
                ('guest_name', models.CharField(blank=True, max_length=200)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('found_date', models.DateField(blank=True, null=True)),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_found_items', to='api.hotel')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hotel', 'status'], name='api_lostfou_hotel_i_3727c5_idx')],
            },
        ),
    ]
