# Generated by Django 5.1.4 on 2026-07-01 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_lostfounditem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('morning', 'صباح'), ('evening', 'مساء'), ('night', 'ليل')], default='morning', max_length=20)),
                ('staff_name', models.CharField(blank=True, max_length=200)),
                ('handover_date', models.DateField(blank=True, null=True)),
                ('occupied_rooms', models.PositiveIntegerField(default=0)),
                ('arrivals', models.PositiveIntegerField(default=0)),
                ('departures', models.PositiveIntegerField(default=0)),
                ('pending_issues', models.TextField(blank=True)),
                ('guest_complaints', models.TextField(blank=True)),
                ('maintenance_notes', models.TextField(blank=True)),
                ('cash_amount', models.CharField(blank=True, max_length=50)),
                ('general_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_handovers', to='api.hotel')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hotel', 'handover_date'], name='api_shiftha_hotel_i_a1e456_idx')],
            },
        ),
    ]
