# Generated by Django 5.1.4 on 2026-07-01 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_shifthandover'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(blank=True, max_length=30)),
                ('source_type', models.CharField(blank=True, max_length=20)),
                ('service_type', models.CharField(blank=True, max_length=20)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('reservation_no', models.CharField(blank=True, max_length=30)),
                ('guest_name', models.CharField(blank=True, max_length=200)),
                ('table_number', models.CharField(blank=True, max_length=20)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('items', models.JSONField(default=list)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('payment_method', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('new', 'جديد'), ('preparing', 'قيد التحضير'), ('ready', 'جاهز'), ('delivered', 'مُسلَّم'), ('cancelled', 'ملغى')], default='new', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_orders', to='api.hotel')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_orders', to='api.reservation')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_orders', to='api.room')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hotel', 'status'], name='api_foodord_hotel_i_256d7f_idx')],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='api.hotel')),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['hotel'], name='api_menuite_hotel_i_f68f28_idx')],
            },
        ),
    ]
