# Generated by Django 5.1.4 on 2026-07-01 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_foodorder_menuitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FolioCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=200)),
                ('room_number', models.CharField(blank=True, max_length=20)),
                ('booking_number', models.CharField(blank=True, max_length=30)),
                ('charge_type', models.CharField(blank=True, max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='SAR', max_length=10)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('charge_date', models.DateField(blank=True, null=True)),
                ('settled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folio_charges', to='api.hotel')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folio_charges', to='api.reservation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hotel', 'settled'], name='api_folioch_hotel_i_610040_idx'), models.Index(fields=['reservation'], name='api_folioch_reserva_479bd8_idx')],
            },
        ),
    ]
