# Generated by Django 5.1.4 on 2026-07-01 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_foliocharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_key', models.CharField(max_length=120)),
                ('flag', models.CharField(choices=[('normal', 'عادي'), ('vip', 'VIP'), ('blacklist', 'محظور')], default='normal', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_profiles', to='api.hotel')),
            ],
            options={
                'indexes': [models.Index(fields=['hotel'], name='api_guestpr_hotel_i_f7483f_idx')],
                'unique_together': {('hotel', 'guest_key')},
            },
        ),
    ]
