# Generated by Django 5.1.4 on 2026-07-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_guestprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='logo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='hotel',
            name='website',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
