# Generated by Django 5.1.4 on 2026-07-01 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_hotel_currency_hotel_logo_hotel_owner_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('actor_role', models.CharField(blank=True, max_length=30)),
                ('action', models.CharField(max_length=60)),
                ('entity_type', models.CharField(blank=True, max_length=40)),
                ('entity_id', models.CharField(blank=True, max_length=40)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api.hotel')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['hotel', '-created_at'], name='api_auditlo_hotel_i_96c6df_idx'), models.Index(fields=['action'], name='api_auditlo_action_0a1743_idx'), models.Index(fields=['entity_type', 'entity_id'], name='api_auditlo_entity__ad4253_idx')],
            },
        ),
    ]
