# Generated by Django 5.1.4 on 2026-07-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='source',
            field=models.CharField(choices=[('booking', 'حجز/إقامة'), ('folio', 'فوليو غرفة'), ('restaurant', 'مطعم'), ('cafeteria', 'كافتريا'), ('extra_service', 'خدمة إضافية'), ('debt_settlement', 'تسوية ذمة'), ('room_account', 'حساب غرفة'), ('other', 'أخرى')], default='booking', max_length=20),
        ),
    ]
