# Generated by Django 5.1.4 on 2026-07-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_payment_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorder',
            name='amount_card',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='amount_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='amount_electronic',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='amount_room',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='foodorder',
            name='room_settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='food_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
