# Generated by Django 5.1.4 on 2026-07-01 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_userprofile_two_factor_enabled_loginchallenge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayClose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField()),
                ('closed_by_name', models.CharField(blank=True, max_length=150)),
                ('snapshot', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_closes', to='api.hotel')),
            ],
            options={
                'ordering': ['-business_date'],
                'indexes': [models.Index(fields=['hotel', '-business_date'], name='api_dayclos_hotel_i_e955ed_idx')],
                'unique_together': {('hotel', 'business_date')},
            },
        ),
    ]
