# Generated by Django 5.1.4 on 2026-07-01 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_dayclose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='agreement_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='web_booking_agreement',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='HotelAgreementAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('accepted_by_name', models.CharField(blank=True, max_length=150)),
                ('agreement_text', models.TextField(blank=True)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_acceptances', to='api.hotel')),
            ],
            options={
                'indexes': [models.Index(fields=['hotel', 'version'], name='api_hotelag_hotel_i_06c297_idx')],
                'unique_together': {('hotel', 'version')},
            },
        ),
    ]
