# Generated by Django 5.1.4 on 2026-07-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_platformsettings_agreement_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='manage_token',
            field=models.CharField(blank=True, max_length=48),
        ),
    ]
