# Generated by Django 5.1.4 on 2026-07-02 01:43

import django.db.models.deletion
from django.db import migrations, models


def backfill_hotel_code(apps, schema_editor):
    """م1: تعبئة كود فندق داخلي فريد FND-{id:04d} للفنادق الموجودة مسبقًا."""
    Hotel = apps.get_model('api', 'Hotel')
    for h in Hotel.objects.filter(code__isnull=True):
        Hotel.objects.filter(pk=h.pk).update(code=f'FND-{h.pk:04d}')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_expense_void_reason_expense_voided_expense_voided_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='check_in_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='cleaning_duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='hotel',
            name='cleaning_mode',
            field=models.CharField(choices=[('auto', 'تلقائي'), ('manual', 'يدوي')], default='manual', max_length=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='web_booking_needs_confirmation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='cleaning_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HotelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('printing', models.JSONField(blank=True, default=dict)),
                ('documents', models.JSONField(blank=True, default=dict)),
                ('notifications', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='op_settings', to='api.hotel')),
            ],
        ),
        migrations.RunPython(backfill_hotel_code, migrations.RunPython.noop),
    ]
