# Generated by Django 5.1.4 on 2026-07-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_hotel_check_in_time_hotel_check_out_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_card',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='amount_electronic',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'نقدًا'), ('electronic', 'إلكتروني'), ('card', 'بطاقة/كرت'), ('transfer', 'تحويل'), ('mixed', 'مختلط'), ('other', 'أخرى')], default='cash', max_length=20),
        ),
    ]
