# Generated by Django 5.1.4 on 2026-07-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_payment_amount_card_payment_amount_cash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='enforce_shift_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='shift_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='shift_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
