# Generated by Django 5.1.4 on 2026-07-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_hotel_enforce_shift_login_staff_shift_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='two_factor_policy',
            field=models.CharField(choices=[('off', 'اختياري (ذاتي)'), ('managers', 'إلزامي للمدير'), ('all', 'إلزامي للجميع')], default='off', max_length=12),
        ),
    ]
