# Generated by Django 5.1.4 on 2026-07-02 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_hotel_two_factor_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
