# Generated by Django 5.1.4 on 2026-07-02 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_room_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostfounditem',
            name='received_by',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lostfounditem',
            name='status',
            field=models.CharField(choices=[('found', 'محفوظ'), ('returned', 'تم تسليمه'), ('unclaimed', 'غير مُطالَب'), ('damaged', 'تالف'), ('unknown', 'غير معروف')], default='found', max_length=20),
        ),
    ]
