# Generated by Django 5.1.4 on 2026-07-02 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_userprofile_avatar_userprofile_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='foliocharge',
            name='void_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='foliocharge',
            name='voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='foliocharge',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foliocharge',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_folio_charges', to=settings.AUTH_USER_MODEL),
        ),
    ]
