# Generated by Django 5.1.4 on 2026-07-02 06:15
# م5: حقل الهاتف المطبّع + تعبئة رجعية للحجوزات القائمة (backfill).

from django.db import migrations, models


def backfill_normalized_phone(apps, schema_editor):
    """تعبئة guest_phone_normalized للحجوزات القائمة من نفس دالة التطبيع المركزية."""
    from api.phone import normalize_phone
    Reservation = apps.get_model('api', 'Reservation')
    for r in (Reservation.objects.exclude(guest_phone='')
              .only('id', 'guest_phone', 'guest_phone_normalized').iterator()):
        norm = normalize_phone(r.guest_phone)
        if norm and r.guest_phone_normalized != norm:
            Reservation.objects.filter(pk=r.pk).update(guest_phone_normalized=norm)


def noop(apps, schema_editor):
    # عكس آمن: لا حاجة لإفراغ الحقل (يبقى بلا ضرر)
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_foliocharge_void_reason_foliocharge_voided_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest_phone_normalized',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.RunPython(backfill_normalized_phone, noop),
    ]
